/**
 * Better Auth Database Schema (Drizzle)
 * 
 * Defines the authentication tables required by Better Auth.
 * These tables are SEPARATE from the existing WTD business tables.
 * 
 * Tables:
 * - auth_users: Customer accounts
 * - auth_sessions: Login sessions
 * - auth_accounts: Authentication credentials (password stored here)
 * - auth_verifications: Email verification and password reset tokens
 * 
 * Naming Convention:
 * - All auth tables prefixed with "auth_" to avoid conflicts
 * - Column names follow Better Auth conventions but use snake_case
 * 
 * @created 2026-08-20
 */

import {
  pgTable,
  text,
  boolean,
  timestamp,
  index,
  uniqueIndex,
  jsonb,
} from "drizzle-orm/pg-core";

import type { SavedQuoteSnapshot } from "./savedQuotes/types";

// ============================================================================
// AUTH_USERS - Customer Accounts
// ============================================================================

/**
 * Customer account records.
 * 
 * Note: This table stores the user identity. The password is stored in
 * auth_accounts (Better Auth's multi-provider design).
 */
export const authUsers = pgTable(
  "auth_users",
  {
    id: text("id").primaryKey(), // UUID, generated by Better Auth
    
    // Identity
    email: text("email").notNull().unique(),
    emailVerified: boolean("email_verified").notNull().default(false),
    name: text("name"),
    image: text("image"), // Profile image URL (optional, for future use)
    
    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    emailIdx: uniqueIndex("auth_users_email_idx").on(table.email),
  })
);

// ============================================================================
// AUTH_SESSIONS - Login Sessions
// ============================================================================

/**
 * Active login sessions.
 * 
 * Each device/browser gets its own session. Sessions are stored in the database
 * (not JWTs) for security and revocability.
 */
export const authSessions = pgTable(
  "auth_sessions",
  {
    id: text("id").primaryKey(), // UUID
    
    // User reference
    userId: text("user_id")
      .notNull()
      .references(() => authUsers.id, { onDelete: "cascade" }),
    
    // Session token (hashed)
    token: text("token").notNull().unique(),
    
    // Expiration
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    
    // Metadata (for security auditing)
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    
    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index("auth_sessions_user_id_idx").on(table.userId),
    tokenIdx: uniqueIndex("auth_sessions_token_idx").on(table.token),
    expiresAtIdx: index("auth_sessions_expires_at_idx").on(table.expiresAt),
  })
);

// ============================================================================
// AUTH_ACCOUNTS - Authentication Credentials
// ============================================================================

/**
 * Authentication credentials.
 * 
 * Better Auth uses this table to support multiple auth providers per user.
 * For email/password auth, the password hash is stored here with
 * providerId = "credential".
 * 
 * This design allows adding OAuth providers later without schema changes.
 */
export const authAccounts = pgTable(
  "auth_accounts",
  {
    id: text("id").primaryKey(), // UUID
    
    // User reference
    userId: text("user_id")
      .notNull()
      .references(() => authUsers.id, { onDelete: "cascade" }),
    
    // Provider identification (Better Auth 1.7+)
    // For email/password: providerId = "credential", issuer = "local:credential", accountId = user.id
    // For OAuth: providerId = "google", issuer = "https://accounts.google.com", accountId = Google sub
    providerId: text("provider_id").notNull(),
    accountId: text("account_id").notNull(),
    issuer: text("issuer").notNull(), // Better Auth 1.7 requirement
    
    // OAuth tokens (null for credential auth)
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    
    // Password (for credential auth only, hashed with scrypt)
    password: text("password"),
    
    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index("auth_accounts_user_id_idx").on(table.userId),
    // Unique constraint: one account per issuer + accountId (Better Auth 1.7+)
    issuerAccountIdx: uniqueIndex("auth_accounts_issuer_account_id_idx").on(
      table.issuer,
      table.accountId
    ),
  })
);

// ============================================================================
// AUTH_VERIFICATIONS - Tokens for Email Verification & Password Reset
// ============================================================================

/**
 * Verification tokens.
 * 
 * Used for:
 * - Email verification after signup
 * - Password reset requests
 * 
 * Tokens are hashed and single-use (deleted after verification).
 */
export const authVerifications = pgTable(
  "auth_verifications",
  {
    id: text("id").primaryKey(), // UUID
    
    // The identifier being verified (usually email address)
    identifier: text("identifier").notNull(),
    
    // The hashed token value
    value: text("value").notNull(),
    
    // Expiration
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    
    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    identifierIdx: index("auth_verifications_identifier_idx").on(table.identifier),
    expiresAtIdx: index("auth_verifications_expires_at_idx").on(table.expiresAt),
  })
);

// ============================================================================
// USER_GARAGE - Saved Vehicles (Account-Backed)
// ============================================================================

/**
 * User's saved garage vehicles.
 * 
 * This table persists vehicles to the server for authenticated users.
 * Each user can have up to 10 vehicles. The garage is synced on login:
 * - Local garage vehicles are merged into server garage (no duplicates)
 * - Server becomes source of truth for authenticated sessions
 * 
 * @created 2026-08-21
 */
export const userGarage = pgTable(
  "user_garage",
  {
    id: text("id").primaryKey(), // Format: v_<timestamp>_<random>
    
    // User reference
    userId: text("user_id")
      .notNull()
      .references(() => authUsers.id, { onDelete: "cascade" }),
    
    // Vehicle identification (required)
    year: text("year").notNull(),
    make: text("make").notNull(),
    model: text("model").notNull(),
    trim: text("trim"),
    modification: text("modification"), // Canonical vehicle ID (e.g., "ford-f-150-2024-xlt")
    
    // Optional metadata
    wheelDia: text("wheel_dia"), // Selected wheel diameter (stored as text for flexibility)
    nickname: text("nickname"), // User-assigned nickname
    
    // Timestamps
    addedAt: timestamp("added_at", { withTimezone: true }).notNull().defaultNow(),
    lastActiveAt: timestamp("last_active_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index("user_garage_user_id_idx").on(table.userId),
    // Composite unique: one vehicle per user per modification (prevents duplicates)
    userModificationIdx: uniqueIndex("user_garage_user_modification_idx").on(
      table.userId,
      table.modification
    ),
  })
);

// ============================================================================
// SAVED_QUOTES - Customer Saved Shopping Configurations
// ============================================================================

/**
 * Customer-saved shopping configurations.
 * 
 * Allows customers to save a cart/package configuration to their account
 * and return to it later from any device. Separate from checkout quotes.
 * 
 * @created 2026-08-24
 */
export const savedQuotes = pgTable(
  "saved_quotes",
  {
    id: text("id").primaryKey(), // Format: sq_<nanoid(21)>
    
    // User reference
    userId: text("user_id")
      .notNull()
      .references(() => authUsers.id, { onDelete: "cascade" }),
    
    // Optional user-assigned name
    name: text("name"),
    
    // Vehicle (denormalized for display)
    vehicleYear: text("vehicle_year"),
    vehicleMake: text("vehicle_make"),
    vehicleModel: text("vehicle_model"),
    vehicleTrim: text("vehicle_trim"),
    vehicleModification: text("vehicle_modification"),
    
    // Immutable configuration snapshot (JSONB in database)
    snapshotJson: jsonb("snapshot_json").$type<SavedQuoteSnapshot>().notNull(),
    
    // Timestamps
    savedAt: timestamp("saved_at", { withTimezone: true }).notNull().defaultNow(),
    lastViewedAt: timestamp("last_viewed_at", { withTimezone: true }),
    
    // Conversion tracking
    convertedOrderId: text("converted_order_id"),
    convertedAt: timestamp("converted_at", { withTimezone: true }),
    
    // Soft delete
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    
    // Idempotency (for serverless concurrency)
    idempotencyKey: text("idempotency_key"),
    
    // Audit
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    userActiveIdx: index("idx_saved_quotes_user_active").on(table.userId),
    // Unique partial index for idempotency (only when key is not null)
    // Note: Drizzle doesn't support partial indexes directly, so we create it in SQL migration
  })
);

// ============================================================================
// PENDING_SAVED_QUOTES - Guest Flow Temporary Storage
// ============================================================================

/**
 * Temporary holding for guest quote saves pending authentication.
 * 
 * When a guest clicks "Save Quote", the validated snapshot is stored here
 * with a secure token. After authentication, the token is claimed and
 * the quote moves to saved_quotes.
 * 
 * @created 2026-08-24
 */
export const pendingSavedQuotes = pgTable(
  "pending_saved_quotes",
  {
    token: text("token").primaryKey(), // Format: psq_<nanoid(32)>
    
    // Validated snapshot (JSONB in database)
    snapshotJson: jsonb("snapshot_json").$type<SavedQuoteSnapshot>().notNull(),
    
    // Vehicle (denormalized)
    vehicleYear: text("vehicle_year"),
    vehicleMake: text("vehicle_make"),
    vehicleModel: text("vehicle_model"),
    vehicleTrim: text("vehicle_trim"),
    vehicleModification: text("vehicle_modification"),
    
    // Tracking
    cartId: text("cart_id"),
    returnTo: text("return_to").notNull().default("/account"),
    
    // Expiration
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    expiresIdx: index("idx_pending_saved_quotes_expires").on(table.expiresAt),
  })
);

// ============================================================================
// Type Exports
// ============================================================================

export type AuthUser = typeof authUsers.$inferSelect;
export type NewAuthUser = typeof authUsers.$inferInsert;

export type AuthSession = typeof authSessions.$inferSelect;
export type NewAuthSession = typeof authSessions.$inferInsert;

export type AuthAccount = typeof authAccounts.$inferSelect;
export type NewAuthAccount = typeof authAccounts.$inferInsert;

export type AuthVerification = typeof authVerifications.$inferSelect;
export type NewAuthVerification = typeof authVerifications.$inferInsert;

export type UserGarageVehicle = typeof userGarage.$inferSelect;
export type NewUserGarageVehicle = typeof userGarage.$inferInsert;

export type SavedQuote = typeof savedQuotes.$inferSelect;
export type NewSavedQuote = typeof savedQuotes.$inferInsert;

export type PendingSavedQuote = typeof pendingSavedQuotes.$inferSelect;
export type NewPendingSavedQuote = typeof pendingSavedQuotes.$inferInsert;
