/**
 * Better Auth Database Schema (Drizzle)
 * 
 * Defines the authentication tables required by Better Auth.
 * These tables are SEPARATE from the existing WTD business tables.
 * 
 * Tables:
 * - auth_users: Customer accounts
 * - auth_sessions: Login sessions
 * - auth_accounts: Authentication credentials (password stored here)
 * - auth_verifications: Email verification and password reset tokens
 * 
 * Naming Convention:
 * - All auth tables prefixed with "auth_" to avoid conflicts
 * - Column names follow Better Auth conventions but use snake_case
 * 
 * @created 2026-08-20
 */

import {
  pgTable,
  text,
  boolean,
  timestamp,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

// ============================================================================
// AUTH_USERS - Customer Accounts
// ============================================================================

/**
 * Customer account records.
 * 
 * Note: This table stores the user identity. The password is stored in
 * auth_accounts (Better Auth's multi-provider design).
 */
export const authUsers = pgTable(
  "auth_users",
  {
    id: text("id").primaryKey(), // UUID, generated by Better Auth
    
    // Identity
    email: text("email").notNull().unique(),
    emailVerified: boolean("email_verified").notNull().default(false),
    name: text("name"),
    image: text("image"), // Profile image URL (optional, for future use)
    
    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    emailIdx: uniqueIndex("auth_users_email_idx").on(table.email),
  })
);

// ============================================================================
// AUTH_SESSIONS - Login Sessions
// ============================================================================

/**
 * Active login sessions.
 * 
 * Each device/browser gets its own session. Sessions are stored in the database
 * (not JWTs) for security and revocability.
 */
export const authSessions = pgTable(
  "auth_sessions",
  {
    id: text("id").primaryKey(), // UUID
    
    // User reference
    userId: text("user_id")
      .notNull()
      .references(() => authUsers.id, { onDelete: "cascade" }),
    
    // Session token (hashed)
    token: text("token").notNull().unique(),
    
    // Expiration
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    
    // Metadata (for security auditing)
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    
    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index("auth_sessions_user_id_idx").on(table.userId),
    tokenIdx: uniqueIndex("auth_sessions_token_idx").on(table.token),
    expiresAtIdx: index("auth_sessions_expires_at_idx").on(table.expiresAt),
  })
);

// ============================================================================
// AUTH_ACCOUNTS - Authentication Credentials
// ============================================================================

/**
 * Authentication credentials.
 * 
 * Better Auth uses this table to support multiple auth providers per user.
 * For email/password auth, the password hash is stored here with
 * providerId = "credential".
 * 
 * This design allows adding OAuth providers later without schema changes.
 */
export const authAccounts = pgTable(
  "auth_accounts",
  {
    id: text("id").primaryKey(), // UUID
    
    // User reference
    userId: text("user_id")
      .notNull()
      .references(() => authUsers.id, { onDelete: "cascade" }),
    
    // Provider identification (Better Auth 1.7+)
    // For email/password: providerId = "credential", issuer = "local:credential", accountId = user.id
    // For OAuth: providerId = "google", issuer = "https://accounts.google.com", accountId = Google sub
    providerId: text("provider_id").notNull(),
    accountId: text("account_id").notNull(),
    issuer: text("issuer").notNull(), // Better Auth 1.7 requirement
    
    // OAuth tokens (null for credential auth)
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    
    // Password (for credential auth only, hashed with scrypt)
    password: text("password"),
    
    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index("auth_accounts_user_id_idx").on(table.userId),
    // Unique constraint: one account per issuer + accountId (Better Auth 1.7+)
    issuerAccountIdx: uniqueIndex("auth_accounts_issuer_account_id_idx").on(
      table.issuer,
      table.accountId
    ),
  })
);

// ============================================================================
// AUTH_VERIFICATIONS - Tokens for Email Verification & Password Reset
// ============================================================================

/**
 * Verification tokens.
 * 
 * Used for:
 * - Email verification after signup
 * - Password reset requests
 * 
 * Tokens are hashed and single-use (deleted after verification).
 */
export const authVerifications = pgTable(
  "auth_verifications",
  {
    id: text("id").primaryKey(), // UUID
    
    // The identifier being verified (usually email address)
    identifier: text("identifier").notNull(),
    
    // The hashed token value
    value: text("value").notNull(),
    
    // Expiration
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    
    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    identifierIdx: index("auth_verifications_identifier_idx").on(table.identifier),
    expiresAtIdx: index("auth_verifications_expires_at_idx").on(table.expiresAt),
  })
);

// ============================================================================
// Type Exports
// ============================================================================

export type AuthUser = typeof authUsers.$inferSelect;
export type NewAuthUser = typeof authUsers.$inferInsert;

export type AuthSession = typeof authSessions.$inferSelect;
export type NewAuthSession = typeof authSessions.$inferInsert;

export type AuthAccount = typeof authAccounts.$inferSelect;
export type NewAuthAccount = typeof authAccounts.$inferInsert;

export type AuthVerification = typeof authVerifications.$inferSelect;
export type NewAuthVerification = typeof authVerifications.$inferInsert;
